## Add your printers below

Infinite Benchy Theorem:
  title: "Infinite Benchy Theorem"
  description: "A belted, enclosed 3D printer designed for 24/7 3D printing"
  repository: "https://raw.githubusercontent.com/qcoral/infinite-benchy-theorem/refs/heads/main/design.md"
  file_name: infinite_benchy_theorem.md
Radeon:
  title: "Radeon"
  description: "A budget-friendly printer designed around CoreXY kinematics and linear rails."
  repository: "https://raw.githubusercontent.com/pmnlla/radeon/refs/heads/master/docs-head.md"
  file_name: pmnlla-radeon.md

3dSpire:
  title: "3d Spire"
  description: "A Core XY printer with linear rails"
  repository: "https://raw.githubusercontent.com/JeffreyWangDev/3dspire/refs/heads/main/design.md"
  file_name: spire.md
  
Quantum One:
  title: "Quantum One"
  description: "An affordable prototyping machine that looks good, performs well, is affordable, and you can build yourself"
  repository: "https://raw.githubusercontent.com/Echo-Labs-Development/Quantum-One/main/plan.md"
  file_name: quantum-one.md

EOS 3D:
  title: "EOS 3D"
  description: "A cheap cantilever 3D printer with full self calibration capabilities."
  repository: "https://raw.githubusercontent.com/AdamTuraj/EOS-3D/refs/heads/main/JOURNAL.md"
  file_name: eos3d.md

Meteroid:
  title: "Meteoroid"
  description: "Production-ready 3d printer based on a Ender 5 frame, with multifunction tool changing. "
  repository: "https://raw.githubusercontent.com/techy-robot/Meteoroid/refs/heads/main/Changelog.md"
  file_name: Meteoroid.md

Mu Draconis:
  title: "Mu Draconis"
  description: "A polar 3d printer with modern hardware, but still not the most practical"
  repository: "https://raw.githubusercontent.com/WilliamPrime/Mu-Draconis/refs/heads/main/design.md"
  file_name: mu-draconis.md

Prism:
  title: "Pr!sm"
  description: "A cheap small 3d printer, a1 mini-like but open source."
  repository: "https://raw.githubusercontent.com/Spectralo/prism/refs/heads/main/README.md"
  file_name: pr!sm.md

Aniprinter:
  title: "Aniprinter"
  description: "A cute anime 3d printer UwU."
  repository: "https://raw.githubusercontent.com/cheyao/aniprinter/refs/heads/main/JOURNAL.md"
  file_name: aniprinter.md

Anixus Vex:
  title: "Anixus Vex"
  description: "A powerful, fast, precise CoreXY 3D printer aimed at intense speed"
  repository: "https://raw.githubusercontent.com/invictus-anic3tus/anixus-vex/refs/heads/main/journal.md"
  file_name: anixus_vex.md

pixl:
  title: "pixl"
  description: "A small corexy 3d printer"
  repository: "https://raw.githubusercontent.com/vibsthebot/pixl/refs/heads/main/design.md"
  file_name: pixl.md
